
---
title: "Use R in Databricks"
output:
  html_document:
    toc: true
---


```{r}
require(SparkR)
```


```{r}
# Read diamonds.csv dataset as SparkDataFrame
diamonds <- read.df("/databricks-datasets/Rdatasets/data-001/csv/ggplot2/diamonds.csv",
                  source = "com.databricks.spark.csv", header="true", inferSchema = "true")
diamonds <- withColumnRenamed(diamonds, "", "rowID")

```


```{r}
# Split data into Training set and Test set
trainingData <- sample(diamonds, FALSE, 0.7)
testData <- except(diamonds, trainingData)
```


```{r}
# Exclude rowIDs
trainingData <- trainingData[, -1]
testData <- testData[, -1]

```


```{r}
print(count(diamonds))
print(count(trainingData))
print(count(testData))
```


```{r}
head(trainingData)
```


```{r}
head(testData)
```


```{r}
# Family = "gaussian" to train a linear regression model
lrModel <- glm(price ~ ., data = trainingData, family = "gaussian")

# Print a summary of the trained model
summary(lrModel)
```


```{r}
# Generate predictions using the trained model
predictions <- predict(lrModel, newData = testData)

# View predictions against mpg column
display(select(predictions, "price", "prediction"))
```


```{r}

```

